services:
  servidor:
    build: ./servidor
    container_name: servidor-desarrollo
    ports:
      - "3000:3000"
    volumes:
      - ./servidor:/app
      - /app/node_modules

  cliente:
    build: ./cliente
    container_name: cliente-desarrollo
    ports:
      - "5173:5173"
    volumes:
      - ./cliente:/app
      - /app/node_modules
    depends_on:
      - servidor